In [1]:
import poppy
import jax
import jax.numpy as jnp
import functools
import galois
import numpy as np

In [2]:
p = 17
n = 3
q = p ** n
f = poppy.field( p, n )
d = 100
a = poppy.random( ( d, d ), f, poppy.seed( 0 ) )
b = poppy.random( ( d, d ), f, poppy.seed( 1 ) )
c = poppy.random( 1, f, poppy.seed( 5) )
a, c

(array shape (1, 100, 100).
 field order  4913.,
 array shape (1, 1, 1).
 field order  4913.)

In [4]:
an = np.array( a.lift )
%timeit ( a.lift % 5 ).block_until_ready( )
%timeit an % 5

559 µs ± 95.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
1.05 ms ± 56.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [62]:
13*29%p

74

In [3]:
ai = a.inv( )
ar = a.reciprocal( )
bi = b.inv( )
ai, bi, ar

(array shape (1, 100, 100).
 field order  4913.,
 array shape (1, 100, 100).
 field order  4913.,
 array shape (1, 100, 100).
 field order  4913.)

In [4]:
print( a.lift[ 0, : 10 ] )
( a - a @ ai @ a @ bi @ b ).lift

[ 9  7 14  7 11  7  0  5  9 12]


Array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
%timeit a.reciprocal( ).lift.block_until_ready( )
%timeit a.trace( ).lift.block_until_ready( )
ar.proj( )

373 ms ± 49.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
62.5 µs ± 2.3 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Array([[25178, 19723, 13005, 28359,  5063,  8210, 17839, 19558, 15281,
        21655, 27245],
       [ 1021,  3223, 13798, 19757, 20005,  4700,  6502,  2920, 22231,
        21908, 17624],
       [ 6201, 10417,  3834,  8231,  4453,  8128, 11518, 13707, 26822,
         9602,  9341],
       [14133, 10246, 11966, 23409, 17770,  5125, 19753,  1505, 11097,
        22602,  9936],
       [26790,  1986, 28439, 11225, 12395,  8927, 19801, 22985, 16064,
         7665,  9482],
       [19623, 16317, 14151, 10184, 29120,  6137, 13444,   712, 10899,
        13309, 21190],
       [14247, 11432, 12549,  9006, 20100, 15279,  1700,  2508,  8308,
        12132,  9371],
       [21833,  8834, 24275,  9901, 26367, 17174, 29346, 20879, 14192,
        25239,  2932],
       [16631, 19441,   375,  9720,  5966,  8425, 15731,  9488,  8417,
        28797,  4338],
       [ 9138, 22525, 17861, 29779, 22083,  9632, 11935,   793, 17730,
          467, 12728],
       [24147, 22582, 18807, 21416,  1405, 21753,  6260, 193

In [27]:
GF = galois.Field( q )
ag = GF( np.array( a.proj( ) ) )
%timeit np.reciprocal( ag )
%timeit np.trace( ag )
np.reciprocal( ag )

55.3 µs ± 1.74 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
131 µs ± 63.9 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


GF([[25178, 19723, 13005, 28359,  5063,  8210, 17839, 19558, 15281,
     21655, 27245],
    [ 1021,  3223, 13798, 19757, 20005,  4700,  6502,  2920, 22231,
     21908, 17624],
    [ 6201, 10417,  3834,  8231,  4453,  8128, 11518, 13707, 26822,
      9602,  9341],
    [14133, 10246, 11966, 23409, 17770,  5125, 19753,  1505, 11097,
     22602,  9936],
    [26790,  1986, 28439, 11225, 12395,  8927, 19801, 22985, 16064,
      7665,  9482],
    [19623, 16317, 14151, 10184, 29120,  6137, 13444,   712, 10899,
     13309, 21190],
    [14247, 11432, 12549,  9006, 20100, 15279,  1700,  2508,  8308,
     12132,  9371],
    [21833,  8834, 24275,  9901, 26367, 17174, 29346, 20879, 14192,
     25239,  2932],
    [16631, 19441,   375,  9720,  5966,  8425, 15731,  9488,  8417,
     28797,  4338],
    [ 9138, 22525, 17861, 29779, 22083,  9632, 11935,   793, 17730,
       467, 12728],
    [24147, 22582, 18807, 21416,  1405, 21753,  6260, 19317, 15752,
     23954, 21957]], order=31^3)

In [17]:
%timeit a.trace( ).lift.block_until_ready( )

39.7 ms ± 15.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
an = np.array( a.lift )
%timeit np.trace( an )

9.06 µs ± 89 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
ag = GF( np.array( a.proj( ) ) )
%timeit np.trace( ag )

170 µs ± 5.19 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
N  = 10000
d  = 2
p  = 7
p1 = 13
p2 = 17
n  = 6
q  = p ** n
f  = poppy.field( p,  n )
F  = poppy.field( p1, d )
FF = poppy.field( p2, n )
a  = jax.random.randint( jax.random.PRNGKey( poppy.SEED + 0 ), ( N, F.n, F.n ), 0,       q, dtype = jnp.int64 )
AA  = jax.random.randint( jax.random.PRNGKey( poppy.SEED + 1 ),  ( F.n * FF.n, F.n * FF.n ), 0, 2 ** 32, dtype = jnp.int64 )
BB  = jax.random.randint( jax.random.PRNGKey( poppy.SEED + 2 ),  ( F.n * FF.n, F.n * FF.n ), 0, 2 ** 32, dtype = jnp.int64 )
A  = jax.random.randint( jax.random.PRNGKey( poppy.SEED + 1 ),  ( FF.n, FF.n ), 0, 2 ** 32, dtype = jnp.int64 )
B  = jax.random.randint( jax.random.PRNGKey( poppy.SEED + 2 ),  ( FF.n, FF.n ), 0, 2 ** 32, dtype = jnp.int64 )

@jax.jit
def poppyhash( a ):
    b = poppy.proj( AA @ a + BB, F )
    c = poppy.proj( A @ b + B, FF )
    return c % ( 4 * N )

liftbatch = jax.vmap( poppy.lift, in_axes = ( 0, None ) )
hashbatch = jax.vmap( poppyhash )

ap = liftbatch( a, f )
h  = hashbatch( ap ).squeeze( )
au = jnp.unique( a, axis = 0 )
hu = jnp.unique( h )
len( au ), len( hu ), F.q, FF.q

(10000, 8832, 169, 24137569)